name: react-native-android-build-apk
on:
  push:
  pull_request:
    branches:
      - vishwajit/typescript-support-changes
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd react-native-in-app-payments-quickstart && npm install
          cd android && chmod +x ./gradlew
          ./gradlew assembleRelease
